// Patch the bundled dsh packages for Electron-as-node and workspace behavior.
//
// 1. Folder-picker worker: upstream dsh reads the picked path with
//    `koffi.view(ptr, len)`, which wraps raw native memory in an external
//    ArrayBuffer. Under ELECTRON_RUN_AS_NODE (how this desktop shell runs the
//    bundled dsh), koffi's error path hits `napi_fatal_error` and the worker
//    process dies with `FATAL ERROR: Error::New napi_get_last_error_info`
//    the moment a folder is selected. Plain Node is unaffected.
// 2. Workspace delete: upstream dsh drops the registration only, so the
//    workspace's conversations resurface under the ungrouped bucket. These
//    patches permanently delete every accounted session (session-persistence
//    delete + jsonl backend delete + registry wiring).
// 3. Session delete: upstream dsh has no way to delete a session. These
//    patches add session.delete end to end (API proxy with a session-live
//    guard, fetch carrier, client runtime) and surface a "删除会话" row action.
// 4. Archive management: upstream dsh has no way to restore an archived
//    session, and the sidebar showed an "已归档" bucket. These patches add
//    workspace.unarchiveSession end to end, move the archived-session list
//    into Settings (unarchive + delete actions), and remove the ungrouped
//    bucket from the sidebar entirely.
//
// The script is the postinstall hook, is idempotent, and becomes a no-op once
// upstream ships its own fixes (the original blocks will no longer match).
// When the dsh dependency is upgraded, delete this script and its package.json
// postinstall entry once the fixes land upstream.
// Usage: node scripts/patch-dsh.mjs
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const PATCHES = [
  {
    file: "../node_modules/@deepseek-ai/dsh-client-ui-workspace/lib/client.js",
    original: "\t\tlet react_jsx_runtime = require(\"react/jsx-runtime\");\n\t\tlet react = require(\"react\");\n\t\tlet _deepseek_ai_dsh_client_ui_primitives = require(\"@deepseek-ai/dsh-client-ui-primitives\");\n\t\t//#region lib/types/client/stores.js\n\t\t/**\n\t\t* The workspace browser's viewing store: the session-list grouping mode,\n",
    fixed: "\t\tlet react_jsx_runtime = require(\"react/jsx-runtime\");\n\t\tlet react = require(\"react\");\n\t\tlet _deepseek_ai_dsh_client_ui_primitives = require(\"@deepseek-ai/dsh-client-ui-primitives\");\n\t\tlet _deepseek_ai_dsh_client_web_react = require(\"@deepseek-ai/dsh-client-web-react\");\n\t\t//#region lib/types/client/stores.js\n\t\t/**\n\t\t* The workspace browser's viewing store: the session-list grouping mode,\n",
  },
  {
    file: "../node_modules/@deepseek-ai/dsh-client-ui-workspace/lib/client.js",
    original: "\t\t}\n\t\t/** Display label for the ungrouped bucket row. */\n\t\tconst UNGROUPED_LABEL = \"Ungrouped\";\n\t\t/**\n\t\t* Directory display label: basename of the path (both separators accepted).\n\t\t* Ungrouped-bucket fallback for surfaces without a workspace title.\n",
    fixed: "\t\t}\n\t\t/** Display label for the ungrouped bucket row. */\n\t\tconst UNGROUPED_LABEL = \"Ungrouped\";\n\t\t/** Group key for the registry-global archived Sessions bucket. */\n\t\tconst ARCHIVED_KEY = \"archived\";\n\t\t/** Display label for the archived bucket row (dictionary copy in the renderer). */\n\t\tconst ARCHIVED_LABEL = \"Archived\";\n\t\t/**\n\t\t* Directory display label: basename of the path (both separators accepted).\n\t\t* Ungrouped-bucket fallback for surfaces without a workspace title.\n",
  },
  {
    file: "../node_modules/@deepseek-ai/dsh-client-ui-workspace/lib/client.js",
    original: "\t\t\t\t}\n\t\t\t\tgroups.push(buildGroup(workspace.workspaceId, workspace.workspaceId, workspace.path, Date.parse(workspace.createdAt), workspace.title, members, \"account\"));\n\t\t\t}\n\t\t\tconst stray = list.ids.map((id) => list.byId[id]).filter((s) => s !== void 0 && !accounted.has(s.id) && sessionVisible(s, list.current, archived));\n\t\t\tif (stray.length > 0) groups.push(buildGroup(\"\", void 0, void 0, void 0, UNGROUPED_LABEL, ungroupedOrder === void 0 ? stray : orderedUngrouped(stray, ungroupedOrder), ungroupedOrder === void 0 ? \"recency\" : \"account\"));\n\t\t\treturn groups;\n\t\t}\n\t\tfunction sessionNode(s, descendants) {\n",
    fixed: "\t\t\t\t}\n\t\t\t\tgroups.push(buildGroup(workspace.workspaceId, workspace.workspaceId, workspace.path, Date.parse(workspace.createdAt), workspace.title, members, \"account\"));\n\t\t\t}\n\t\t\treturn groups;\n\t\t}\n\t\tfunction sessionNode(s, descendants) {\n",
  },
  {
    file: "../node_modules/@deepseek-ai/dsh-client-ui-workspace/lib/client.js",
    original: "\t\t\t\t\tsessionCount: g.sessions.length,\n\t\t\t\t\texpanded,\n\t\t\t\t\tcontainsCurrent: g.key === currentGroup,\n\t\t\t\t\tsessions: expanded ? g.sessions.map((session) => sessionNode(session, descendants)) : []\n\t\t\t\t});\n\t\t\t}\n\t\t\treturn groups;\n\t\t}\n\t\t/**\n",
    fixed: "\t\t\t\t\tsessionCount: g.sessions.length,\n\t\t\t\t\texpanded,\n\t\t\t\t\tcontainsCurrent: g.key === currentGroup,\n\t\t\t\t\tarchived: false,\n\t\t\t\t\tsessions: expanded ? g.sessions.map((session) => sessionNode(session, descendants)) : []\n\t\t\t\t});\n\t\t\t}\n\t\t\t// Archived sessions are managed from Settings, not the sidebar tree.\n\t\t\treturn groups;\n\t\t}\n\t\t/**\n",
  },
  {
    file: "../node_modules/@deepseek-ai/dsh-client-ui-workspace/lib/client.js",
    original: "\t\t*/\n\t\tfunction ProjectRowItem({ group, onToggle, onCreate, actions, drag, t }) {\n\t\t\tconst row = group;\n\t\t\tconst label = row.workspaceId === void 0 ? t(\"group.ungrouped\") : row.label;\n\t\t\tconst active = group.expanded && group.containsCurrent;\n\t\t\tconst [menuOpen, setMenuOpen] = (0, react.useState)(false);\n\t\t\tconst workspaceMenuItems = [{\n",
    fixed: "\t\t*/\n\t\tfunction ProjectRowItem({ group, onToggle, onCreate, actions, drag, t }) {\n\t\t\tconst row = group;\n\t\t\tconst label = row.workspaceId === void 0 ? row.archived ? t(\"group.archived\") : t(\"group.ungrouped\") : row.label;\n\t\t\tconst active = group.expanded && group.containsCurrent;\n\t\t\tconst [menuOpen, setMenuOpen] = (0, react.useState)(false);\n\t\t\tconst workspaceMenuItems = [{\n",
  },
  {
    file: "../node_modules/@deepseek-ai/dsh-client-ui-workspace/lib/client.js",
    original: "\t\t* @param props.t - the browser root's locale seat.\n\t\t* @returns the session row.\n\t\t*/\n\t\tfunction SessionNodeItem({ node, currentId, now, onOpen, onRename, onFork, onArchive, drag, flat = false, t }) {\n\t\t\tconst row = node;\n\t\t\tconst title = displayTitle(node, t);\n\t\t\tconst selected = node.id === currentId;\n",
    fixed: "\t\t* @param props.t - the browser root's locale seat.\n\t\t* @returns the session row.\n\t\t*/\n\t\tfunction SessionNodeItem({ node, currentId, now, onOpen, onRename, onFork, onArchive, onUnarchive, onDelete, archived = false, drag, flat = false, t }) {\n\t\t\tconst row = node;\n\t\t\tconst title = displayTitle(node, t);\n\t\t\tconst selected = node.id === currentId;\n",
  },
  {
    file: "../node_modules/@deepseek-ai/dsh-client-ui-workspace/lib/client.js",
    original: "\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\tid: \"archive\",\n\t\t\t\t\tlabel: t(\"menu.archiveSession\"),\n\t\t\t\t\ticon: (0, react_jsx_runtime.jsx)(_deepseek_ai_dsh_client_ui_primitives.IconArchiveOutline20, { size: 16 })\n\t\t\t\t}\n\t\t\t];\n\t\t\treturn (0, react_jsx_runtime.jsx)(_deepseek_ai_dsh_client_ui_primitives.HoverCard, {\n",
    fixed: "\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\tid: \"archive\",\n\t\t\t\t\tlabel: t(archived ? \"menu.unarchiveSession\" : \"menu.archiveSession\"),\n\t\t\t\t\ticon: (0, react_jsx_runtime.jsx)(_deepseek_ai_dsh_client_ui_primitives.IconArchiveOutline20, { size: 16 })\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\ttype: \"separator\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\tid: \"delete\",\n\t\t\t\t\tlabel: t(\"menu.deleteSession\"),\n\t\t\t\t\ticon: (0, react_jsx_runtime.jsx)(_deepseek_ai_dsh_client_ui_primitives.IconTrashOutline16, {}),\n\t\t\t\t\tdanger: true\n\t\t\t\t}\n\t\t\t];\n\t\t\treturn (0, react_jsx_runtime.jsx)(_deepseek_ai_dsh_client_ui_primitives.HoverCard, {\n",
  },
  {
    file: "../node_modules/@deepseek-ai/dsh-client-ui-workspace/lib/client.js",
    original: "\t\t\t\t\t\t\t\t\tsetMenuOpen(false);\n\t\t\t\t\t\t\t\t\tif (id === \"rename\") onRename(node.id, row.title);\n\t\t\t\t\t\t\t\t\tif (id === \"fork\") onFork(node.id);\n\t\t\t\t\t\t\t\t\tif (id === \"archive\") onArchive(node.id);\n\t\t\t\t\t\t\t\t},\n\t\t\t\t\t\t\t\tportal: true,\n\t\t\t\t\t\t\t\tcloseOnPointerLeave: true,\n",
    fixed: "\t\t\t\t\t\t\t\t\tsetMenuOpen(false);\n\t\t\t\t\t\t\t\t\tif (id === \"rename\") onRename(node.id, row.title);\n\t\t\t\t\t\t\t\t\tif (id === \"fork\") onFork(node.id);\n\t\t\t\t\t\t\t\t\tif (id === \"archive\") archived ? onUnarchive?.(node.id) : onArchive(node.id);\n\t\t\t\t\t\t\t\tif (id === \"delete\") onDelete(node.id, row.title);\n\t\t\t\t\t\t\t\t},\n\t\t\t\t\t\t\t\tportal: true,\n\t\t\t\t\t\t\t\tcloseOnPointerLeave: true,\n",
  },
  {
    file: "../node_modules/@deepseek-ai/dsh-client-ui-workspace/lib/client.js",
    original: "\t\t\treturn e.clientY < rect.top + rect.height / 2 ? \"before\" : \"after\";\n\t\t}\n\t\t/** The scrolling session tree; unmounting drops the sessions subscription and expand-all state. */\n\t\tfunction SessionTree({ useSessions, startSession, open, forkSession, workspaces, archivedSessionIds, onRenameRequest, onDeleteRequest, onSessionRename, onSessionArchive, insertWorkspaceBefore, insertSessionBefore, orderBy, groupExpansion, setGroupExpanded, sessionOrderByAccount, sessionUpdatedAtByAccount, syncSessionOrderAccount, setSessionOrder, t }) {\n\t\t\tconst list = useSessions((s) => s);\n\t\t\tconst current = list.current;\n\t\t\tconst [expandedSessionGroups, setExpandedSessionGroups] = (0, react.useState)([]);\n",
    fixed: "\t\t\treturn e.clientY < rect.top + rect.height / 2 ? \"before\" : \"after\";\n\t\t}\n\t\t/** The scrolling session tree; unmounting drops the sessions subscription and expand-all state. */\n\t\tfunction SessionTree({ useSessions, startSession, open, forkSession, workspaces, archivedSessionIds, onRenameRequest, onDeleteRequest, onSessionRename, onSessionArchive, onSessionUnarchive, onSessionDelete, insertWorkspaceBefore, insertSessionBefore, orderBy, groupExpansion, setGroupExpanded, sessionOrderByAccount, sessionUpdatedAtByAccount, syncSessionOrderAccount, setSessionOrder, t }) {\n\t\t\tconst list = useSessions((s) => s);\n\t\t\tconst current = list.current;\n\t\t\tconst [expandedSessionGroups, setExpandedSessionGroups] = (0, react.useState)([]);\n",
  },
  {
    file: "../node_modules/@deepseek-ai/dsh-client-ui-workspace/lib/client.js",
    original: "\t\t\t\t\t\t\t\t\t\t\tonRename: onSessionRename,\n\t\t\t\t\t\t\t\t\t\t\tonFork: forkSession,\n\t\t\t\t\t\t\t\t\t\t\tonArchive: onSessionArchive,\n\t\t\t\t\t\t\t\t\t\t\tdrag: {\n\t\t\t\t\t\t\t\t\t\t\t\tstart: () => {\n\t\t\t\t\t\t\t\t\t\t\t\t\tsessionDropCommitted.current = false;\n\t\t\t\t\t\t\t\t\t\t\t\t\tsetDrag({\n",
    fixed: "\t\t\t\t\t\t\t\t\t\t\tonRename: onSessionRename,\n\t\t\t\t\t\t\t\t\t\t\tonFork: forkSession,\n\t\t\t\t\t\t\t\t\t\t\tonArchive: onSessionArchive,\n\t\t\t\t\t\t\t\t\t\t\tonUnarchive: onSessionUnarchive,\n\t\t\t\t\t\t\t\t\t\t\tonDelete: onSessionDelete,\n\t\t\t\t\t\t\t\t\t\t\tarchived: group.archived,\n\t\t\t\t\t\t\t\t\t\t\tdrag: group.archived ? void 0 : {\n\t\t\t\t\t\t\t\t\t\t\t\tstart: () => {\n\t\t\t\t\t\t\t\t\t\t\t\t\tsessionDropCommitted.current = false;\n\t\t\t\t\t\t\t\t\t\t\t\t\tsetDrag({\n",
  },
  {
    file: "../node_modules/@deepseek-ai/dsh-client-ui-workspace/lib/client.js",
    original: "\t\t\t});\n\t\t}\n\t\t/** The flat \"In one list\" body: every session is one draggable top-level row. */\n\t\tfunction FlatList({ useSessions, open, forkSession, onSessionRename, onSessionArchive, archivedSessionIds, orderBy, sessionOrderByAccount, sessionUpdatedAtByAccount, syncSessionOrderAccount, setSessionOrder, t }) {\n\t\t\tconst list = useSessions((s) => s);\n\t\t\tconst baseRows = (0, react.useMemo)(() => deriveFlat(list, archivedSessionIds), [list, archivedSessionIds]);\n\t\t\tconst sessionIds = (0, react.useMemo)(() => baseRows.map((row) => row.id), [baseRows]);\n",
    fixed: "\t\t\t});\n\t\t}\n\t\t/** The flat \"In one list\" body: every session is one draggable top-level row. */\n\t\tfunction FlatList({ useSessions, open, forkSession, onSessionRename, onSessionArchive, onSessionDelete, archivedSessionIds, orderBy, sessionOrderByAccount, sessionUpdatedAtByAccount, syncSessionOrderAccount, setSessionOrder, t }) {\n\t\t\tconst list = useSessions((s) => s);\n\t\t\tconst baseRows = (0, react.useMemo)(() => deriveFlat(list, archivedSessionIds), [list, archivedSessionIds]);\n\t\t\tconst sessionIds = (0, react.useMemo)(() => baseRows.map((row) => row.id), [baseRows]);\n",
  },
  {
    file: "../node_modules/@deepseek-ai/dsh-client-ui-workspace/lib/client.js",
    original: "\t\t\t\t\t\t\tonRename: onSessionRename,\n\t\t\t\t\t\t\tonFork: forkSession,\n\t\t\t\t\t\t\tonArchive: onSessionArchive,\n\t\t\t\t\t\t\tflat: true,\n\t\t\t\t\t\t\tdrag: {\n\t\t\t\t\t\t\t\tstart: () => {\n",
    fixed: "\t\t\t\t\t\t\tonRename: onSessionRename,\n\t\t\t\t\t\t\tonFork: forkSession,\n\t\t\t\t\t\t\tonArchive: onSessionArchive,\n\t\t\t\t\t\t\tonDelete: onSessionDelete,\n\t\t\t\t\t\t\tflat: true,\n\t\t\t\t\t\t\tdrag: {\n\t\t\t\t\t\t\t\tstart: () => {\n",
  },
  {
    file: "../node_modules/@deepseek-ai/dsh-client-ui-workspace/lib/client.js",
    original: "\t\t* @param props - composed slot props (shell owner share + store + injected actions).\n\t\t* @returns the region element tree.\n\t\t*/\n\t\tfunction WorkspaceBrowser({ wide, expandSidebar, useSessions, useWorkspaces, useStore, actions, startSession, open, renameSession, forkSession, renameWorkspace, deleteWorkspace, insertWorkspaceBefore, archiveSession, insertSessionBefore, createWorkspace, searchSessions, searchResultLimit, useDirectoryFlow, renderSlot, t }) {\n\t\t\tconst workspaces = useWorkspaces((state) => state.items);\n\t\t\tconst workspacePhase = useWorkspaces((state) => state.phase);\n\t\t\tconst archivedSessionIds = useWorkspaces((state) => state.archivedSessionIds);\n",
    fixed: "\t\t* @param props - composed slot props (shell owner share + store + injected actions).\n\t\t* @returns the region element tree.\n\t\t*/\n\t\tfunction WorkspaceBrowser({ wide, expandSidebar, useSessions, useWorkspaces, useStore, actions, startSession, open, renameSession, forkSession, renameWorkspace, deleteWorkspace, insertWorkspaceBefore, archiveSession, unarchiveSession, deleteSession, insertSessionBefore, createWorkspace, searchSessions, searchResultLimit, useDirectoryFlow, renderSlot, t }) {\n\t\t\tconst workspaces = useWorkspaces((state) => state.items);\n\t\t\tconst workspacePhase = useWorkspaces((state) => state.phase);\n\t\t\tconst archivedSessionIds = useWorkspaces((state) => state.archivedSessionIds);\n",
  },
  {
    file: "../node_modules/@deepseek-ai/dsh-client-ui-workspace/lib/client.js",
    original: "\t\t\t\t\tconsole.warn(\"session archive rejected:\", reason);\n\t\t\t\t});\n\t\t\t};\n\t\t\tconst [deleteTarget, setDeleteTarget] = (0, react.useState)(null);\n\t\t\tconst [deleting, setDeleting] = (0, react.useState)(false);\n\t\t\tconst [deleteCommittedId, setDeleteCommittedId] = (0, react.useState)(null);\n",
    fixed: "\t\t\t\t\tconsole.warn(\"session archive rejected:\", reason);\n\t\t\t\t});\n\t\t\t};\n\t\t\tconst onSessionUnarchive = (sessionId) => {\n\t\t\t\tunarchiveSession(sessionId).catch((reason) => {\n\t\t\t\t\tconsole.warn(\"session unarchive rejected:\", reason);\n\t\t\t\t});\n\t\t\t};\n\t\t\tconst [deleteSessionTarget, setDeleteSessionTarget] = (0, react.useState)(null);\n\t\t\tconst [deletingSession, setDeletingSession] = (0, react.useState)(false);\n\t\t\tconst [deleteSessionError, setDeleteSessionError] = (0, react.useState)(null);\n\t\t\tconst onSessionDelete = (sessionId, title) => {\n\t\t\t\tsetDeleteSessionTarget({ sessionId, title });\n\t\t\t\tsetDeleteSessionError(null);\n\t\t\t};\n\t\t\tconst confirmDeleteSession = () => {\n\t\t\t\tif (deleteSessionTarget === null) return;\n\t\t\t\tsetDeletingSession(true);\n\t\t\t\tdeleteSession(deleteSessionTarget.sessionId).then(() => {\n\t\t\t\t\tsetDeletingSession(false);\n\t\t\t\t\tsetDeleteSessionTarget(null);\n\t\t\t\t}).catch((reason) => {\n\t\t\t\t\tsetDeletingSession(false);\n\t\t\t\t\tsetDeleteSessionError(reason instanceof Error ? reason.message : String(reason));\n\t\t\t\t});\n\t\t\t};\n\t\t\tconst closeDeleteSession = () => {\n\t\t\t\tif (deletingSession) return;\n\t\t\t\tsetDeleteSessionTarget(null);\n\t\t\t\tsetDeleteSessionError(null);\n\t\t\t};\n\t\t\tconst [deleteTarget, setDeleteTarget] = (0, react.useState)(null);\n\t\t\tconst [deleting, setDeleting] = (0, react.useState)(false);\n\t\t\tconst [deleteCommittedId, setDeleteCommittedId] = (0, react.useState)(null);\n",
  },
  {
    file: "../node_modules/@deepseek-ai/dsh-client-ui-workspace/lib/client.js",
    original: "\t\t\t\t\t\t\tforkSession,\n\t\t\t\t\t\t\tonSessionRename,\n\t\t\t\t\t\t\tonSessionArchive,\n\t\t\t\t\t\t\tarchivedSessionIds,\n\t\t\t\t\t\t\torderBy,\n\t\t\t\t\t\t\tsessionOrderByAccount,\n",
    fixed: "\t\t\t\t\t\t\tforkSession,\n\t\t\t\t\t\t\tonSessionRename,\n\t\t\t\t\t\t\tonSessionArchive,\n\t\t\t\t\t\t\tonSessionDelete,\n\t\t\t\t\t\t\tarchivedSessionIds,\n\t\t\t\t\t\t\torderBy,\n\t\t\t\t\t\t\tsessionOrderByAccount,\n",
  },
  {
    file: "../node_modules/@deepseek-ai/dsh-client-ui-workspace/lib/client.js",
    original: "\t\t\t\t\t\t\tuseSessions,\n\t\t\t\t\t\t\tonSessionRename,\n\t\t\t\t\t\t\tonSessionArchive,\n\t\t\t\t\t\t\tforkSession,\n\t\t\t\t\t\t\tworkspaces,\n\t\t\t\t\t\t\tgroupExpansion,\n",
    fixed: "\t\t\t\t\t\t\tuseSessions,\n\t\t\t\t\t\t\tonSessionRename,\n\t\t\t\t\t\t\tonSessionArchive,\n\t\t\t\t\t\t\tonSessionUnarchive,\n\t\t\t\t\t\t\tonSessionDelete,\n\t\t\t\t\t\t\tforkSession,\n\t\t\t\t\t\t\tworkspaces,\n\t\t\t\t\t\t\tgroupExpansion,\n",
  },
  {
    file: "../node_modules/@deepseek-ai/dsh-client-ui-workspace/lib/client.js",
    original: "\t\t\t\t\t\t\trole: \"alert\",\n\t\t\t\t\t\t\tchildren: deleteError\n\t\t\t\t\t\t})]\n\t\t\t\t\t})\n\t\t\t\t]\n\t\t\t});\n",
    fixed: "\t\t\t\t\t\t\trole: \"alert\",\n\t\t\t\t\t\t\tchildren: deleteError\n\t\t\t\t\t\t})]\n\t\t\t\t\t}),\n\t\t\t\t\t(0, react_jsx_runtime.jsxs)(_deepseek_ai_dsh_client_ui_primitives.Modal, {\n\t\t\t\t\t\topen: deleteSessionTarget !== null,\n\t\t\t\t\t\tonClose: closeDeleteSession,\n\t\t\t\t\t\tcloseLabel: t(\"close\"),\n\t\t\t\t\t\ttitle: t(\"menu.deleteSession\"),\n\t\t\t\t\t\t...deleteSessionTarget === null ? {} : { description: t(\"deleteSession.confirm\", { name: deleteSessionTarget.title }) },\n\t\t\t\t\t\tfooter: (0, react_jsx_runtime.jsxs)(react_jsx_runtime.Fragment, { children: [(0, react_jsx_runtime.jsx)(_deepseek_ai_dsh_client_ui_primitives.Button, {\n\t\t\t\t\t\t\tvariant: \"outline\",\n\t\t\t\t\t\t\tdisabled: deletingSession,\n\t\t\t\t\t\t\tonClick: closeDeleteSession,\n\t\t\t\t\t\t\tchildren: t(\"cancel\")\n\t\t\t\t\t\t}), (0, react_jsx_runtime.jsx)(_deepseek_ai_dsh_client_ui_primitives.Button, {\n\t\t\t\t\t\t\tvariant: \"outline\",\n\t\t\t\t\t\t\tclassName: WorkspaceBrowser_module_css_default.deleteAction,\n\t\t\t\t\t\t\tdisabled: deletingSession,\n\t\t\t\t\t\t\tonClick: confirmDeleteSession,\n\t\t\t\t\t\t\tchildren: t(\"menu.deleteSession\")\n\t\t\t\t\t\t})] }),\n\t\t\t\t\t\tchildren: [deletingSession && (0, react_jsx_runtime.jsx)(\"div\", {\n\t\t\t\t\t\t\tclassName: WorkspaceBrowser_module_css_default.deleteStatus,\n\t\t\t\t\t\t\trole: \"status\",\n\t\t\t\t\t\t\tchildren: t(\"deleteSession.pending\")\n\t\t\t\t\t\t}), deleteSessionError !== null && (0, react_jsx_runtime.jsx)(\"div\", {\n\t\t\t\t\t\t\tclassName: WorkspaceBrowser_module_css_default.renameError,\n\t\t\t\t\t\t\trole: \"alert\",\n\t\t\t\t\t\t\tchildren: deleteSessionError\n\t\t\t\t\t\t})]\n\t\t\t\t\t})\n\t\t\t\t]\n\t\t\t});\n",
  },
  {
    file: "../node_modules/@deepseek-ai/dsh-client-ui-workspace/lib/client.js",
    original: "\t\t/** Simplified Chinese dictionary (the key-set source of truth). */\n\t\tconst zh = {\n\t\t\t\"group.ungrouped\": \"未分组\",\n\t\t\t\"session.new\": \"新会话\",\n\t\t\t\"section.workspaces\": \"工作区\",\n\t\t\t\"section.sessions\": \"会话\",\n",
    fixed: "\t\t/** Simplified Chinese dictionary (the key-set source of truth). */\n\t\tconst zh = {\n\t\t\t\"group.ungrouped\": \"未分组\",\n\t\t\"group.archived\": \"已归档\",\n\t\t\t\"session.new\": \"新会话\",\n\t\t\t\"section.workspaces\": \"工作区\",\n\t\t\t\"section.sessions\": \"会话\",\n",
  },
  {
    file: "../node_modules/@deepseek-ai/dsh-client-ui-workspace/lib/client.js",
    original: "\t\t\t\"field.workspaceName\": \"工作区名称\",\n\t\t\t\"field.sessionName\": \"会话名称\",\n\t\t\t\"delete.workspace\": \"删除工作区\",\n\t\t\t\"delete.desc\": \"将把“{name}”从工作区列表中移除。文件夹与会话记录会保留，其会话将显示在“未分组”下。\",\n\t\t\t\"delete.pending\": \"正在删除工作区…\",\n\t\t\t\"menu.fork\": \"分叉会话\",\n\t\t\t\"menu.archiveSession\": \"归档会话\",\n\t\t\t\"sessions.count.one\": \"{n} 个会话\",\n\t\t\t\"sessions.count.other\": \"{n} 个会话\",\n\t\t\t\"actions.workspace.aria\": \"工作区“{name}”的操作\",\n",
    fixed: "\t\t\t\"field.workspaceName\": \"工作区名称\",\n\t\t\t\"field.sessionName\": \"会话名称\",\n\t\t\t\"delete.workspace\": \"删除工作区\",\n\t\t\t\"delete.desc\": \"将把“{name}”从工作区列表中移除，其下所有对话将被永久删除，此操作不可恢复。文件夹本身会保留。\",\n\t\t\t\"delete.pending\": \"正在删除工作区…\",\n\t\t\t\"menu.fork\": \"分叉会话\",\n\t\t\t\"menu.archiveSession\": \"归档会话\",\n\t\t\"menu.unarchiveSession\": \"取消归档\",\n\t\t\t\"menu.deleteSession\": \"删除会话\",\n\t\t\t\"deleteSession.confirm\": \"确定要删除会话“{name}”吗？其消息记录将被永久删除，此操作不可恢复。\",\n\t\t\t\"deleteSession.pending\": \"正在删除会话…\",\n\t\t\t\"settings.archivedSessions\": \"已归档对话\",\n\t\t\t\"settings.archivedEmpty\": \"暂无已归档的对话\",\n\t\t\t\"sessions.count.one\": \"{n} 个会话\",\n\t\t\t\"sessions.count.other\": \"{n} 个会话\",\n\t\t\t\"actions.workspace.aria\": \"工作区“{name}”的操作\",\n",
  },
  {
    file: "../node_modules/@deepseek-ai/dsh-client-ui-workspace/lib/client.js",
    original: "\t\t/** English dictionary, checked complete against the zh key set. */\n\t\tconst en = {\n\t\t\t\"group.ungrouped\": \"Ungrouped\",\n\t\t\t\"session.new\": \"New Session\",\n\t\t\t\"section.workspaces\": \"Workspaces\",\n\t\t\t\"section.sessions\": \"Sessions\",\n",
    fixed: "\t\t/** English dictionary, checked complete against the zh key set. */\n\t\tconst en = {\n\t\t\t\"group.ungrouped\": \"Ungrouped\",\n\t\t\"group.archived\": \"Archived\",\n\t\t\t\"session.new\": \"New Session\",\n\t\t\t\"section.workspaces\": \"Workspaces\",\n\t\t\t\"section.sessions\": \"Sessions\",\n",
  },
  {
    file: "../node_modules/@deepseek-ai/dsh-client-ui-workspace/lib/client.js",
    original: "\t\t\t\"field.workspaceName\": \"Workspace name\",\n\t\t\t\"field.sessionName\": \"Session name\",\n\t\t\t\"delete.workspace\": \"Delete workspace\",\n\t\t\t\"delete.desc\": \"This removes “{name}” from the workspace list. The folder and session logs will be kept. Its sessions will appear under Ungrouped.\",\n\t\t\t\"delete.pending\": \"Deleting workspace…\",\n\t\t\t\"menu.fork\": \"Fork session\",\n\t\t\t\"menu.archiveSession\": \"Archive session\",\n\t\t\t\"sessions.count.one\": \"{n} session\",\n\t\t\t\"sessions.count.other\": \"{n} sessions\",\n\t\t\t\"actions.workspace.aria\": \"Workspace actions for {name}\",\n",
    fixed: "\t\t\t\"field.workspaceName\": \"Workspace name\",\n\t\t\t\"field.sessionName\": \"Session name\",\n\t\t\t\"delete.workspace\": \"Delete workspace\",\n\t\t\t\"delete.desc\": \"This removes “{name}” from the workspace list and permanently deletes all of its conversations. This cannot be undone. The folder itself is kept.\",\n\t\t\t\"delete.pending\": \"Deleting workspace…\",\n\t\t\t\"menu.fork\": \"Fork session\",\n\t\t\t\"menu.archiveSession\": \"Archive session\",\n\t\t\"menu.unarchiveSession\": \"Unarchive\",\n\t\t\t\"menu.deleteSession\": \"Delete session\",\n\t\t\t\"deleteSession.confirm\": \"Delete session “{name}”? Its messages will be permanently deleted. This cannot be undone.\",\n\t\t\t\"deleteSession.pending\": \"Deleting session…\",\n\t\t\t\"settings.archivedSessions\": \"Archived sessions\",\n\t\t\t\"settings.archivedEmpty\": \"No archived sessions\",\n\t\t\t\"sessions.count.one\": \"{n} session\",\n\t\t\t\"sessions.count.other\": \"{n} sessions\",\n\t\t\t\"actions.workspace.aria\": \"Workspace actions for {name}\",\n",
  },
  {
    file: "../node_modules/@deepseek-ai/dsh-client-ui-workspace/lib/client.js",
    original: "\t\t* framework's global hooks.\n\t\t* @param ctx - client root context.\n\t\t*/\n\t\tfunction apply(ctx) {\n\t\t\tctx.effect(() => ctx.locale.register(NS, {\n\t\t\t\tzh,\n",
    fixed: "\t\t* framework's global hooks.\n\t\t* @param ctx - client root context.\n\t\t*/\n\t\tfunction ArchivedSessionsSection({ useArchived, useSessionsList, unarchiveSession, deleteSession, t }) {\n\t\t\tconst [busy, setBusy] = react.useState(null);\n\t\t\tconst archived = useArchived((state) => state.archivedSessionIds);\n\t\t\tconst sessions = useSessionsList((state) => state);\n\t\t\tconst rows = archived.map((id) => ({\n\t\t\t\tid,\n\t\t\t\ttitle: sessions.byId[id]?.displayTitle ?? String(id)\n\t\t\t}));\n\t\t\tif (rows.length === 0) {\n\t\t\t\treturn react_jsx_runtime.jsx(\"div\", {\n\t\t\t\t\tchildren: t(\"settings.archivedEmpty\")\n\t\t\t\t});\n\t\t\t}\n\t\t\tconst run = (id, action) => {\n\t\t\t\tsetBusy(id);\n\t\t\t\taction(id).catch((reason) => {\n\t\t\t\t\tconsole.warn(\"archived-session action rejected:\", reason);\n\t\t\t\t}).finally(() => {\n\t\t\t\t\tsetBusy(null);\n\t\t\t\t});\n\t\t\t};\n\t\t\treturn react_jsx_runtime.jsx(\"div\", {\n\t\t\t\tchildren: rows.map((row) => react_jsx_runtime.jsxs(\"div\", {\n\t\t\t\t\tkey: String(row.id),\n\t\t\t\t\tchildren: [react_jsx_runtime.jsx(\"span\", {\n\t\t\t\t\t\tchildren: row.title\n\t\t\t\t\t}), react_jsx_runtime.jsx(_deepseek_ai_dsh_client_ui_primitives.Button, {\n\t\t\t\t\t\tvariant: \"outline\",\n\t\t\t\t\t\tdisabled: busy !== null,\n\t\t\t\t\t\tonClick: () => {\n\t\t\t\t\t\t\trun(row.id, unarchiveSession);\n\t\t\t\t\t\t},\n\t\t\t\t\t\tchildren: t(\"menu.unarchiveSession\")\n\t\t\t\t\t}), react_jsx_runtime.jsx(_deepseek_ai_dsh_client_ui_primitives.Button, {\n\t\t\t\t\t\tvariant: \"outline\",\n\t\t\t\t\t\tdisabled: busy !== null,\n\t\t\t\t\t\tonClick: () => {\n\t\t\t\t\t\t\trun(row.id, deleteSession);\n\t\t\t\t\t\t},\n\t\t\t\t\t\tchildren: t(\"menu.deleteSession\")\n\t\t\t\t\t})]\n\t\t\t\t}))\n\t\t\t});\n\t\t}\n\t\tfunction apply(ctx) {\n\t\t\tctx.effect(() => ctx.locale.register(NS, {\n\t\t\t\tzh,\n",
  },
  {
    file: "../node_modules/@deepseek-ai/dsh-client-ui-workspace/lib/client.js",
    original: "\t\t\t\tarchiveSession: async (sessionId) => {\n\t\t\t\t\tawait ctx.workspaces.archiveSession(sessionId);\n\t\t\t\t},\n\t\t\t\tinsertSessionBefore: async (workspaceId, sessionId, beforeSessionId) => {\n\t\t\t\t\tawait ctx.workspaces.insertSessionBefore(workspaceId, sessionId, beforeSessionId);\n\t\t\t\t},\n",
    fixed: "\t\t\t\tarchiveSession: async (sessionId) => {\n\t\t\t\t\tawait ctx.workspaces.archiveSession(sessionId);\n\t\t\t\t},\n\t\t\t\tunarchiveSession: async (sessionId) => {\n\t\t\t\t\tawait ctx.workspaces.unarchiveSession(sessionId);\n\t\t\t\t},\n\t\t\t\tdeleteSession: async (sessionId) => {\n\t\t\t\t\tawait ctx.workspaces.deleteSession(sessionId);\n\t\t\t\t},\n\t\t\t\tinsertSessionBefore: async (workspaceId, sessionId, beforeSessionId) => {\n\t\t\t\t\tawait ctx.workspaces.insertSessionBefore(workspaceId, sessionId, beforeSessionId);\n\t\t\t\t},\n",
  },
  {
    file: "../node_modules/@deepseek-ai/dsh-client-ui-workspace/lib/client.js",
    original: "\t\t\t\tinject: pickerInjected,\n\t\t\t\tlocale: NS\n\t\t\t}, WorkspacePicker));\n\t\t}\n\t\t//#endregion\n\t\texports.apply = apply;\n",
    fixed: "\t\t\t\tinject: pickerInjected,\n\t\t\t\tlocale: NS\n\t\t\t}, WorkspacePicker));\n\t\t\tconst t = ctx.locale.bind(NS);\n\t\t\tconst useArchived = (0, _deepseek_ai_dsh_client_web_react.bindSnapshotSelector)(ctx.workspaces.list);\n\t\t\tconst useSessionsList = (0, _deepseek_ai_dsh_client_web_react.bindSnapshotSelector)(ctx.sessions.list);\n\t\t\tctx.slots.inject(\"settings.section\", () => ctx.slots.register({\n\t\t\t\tname: \"settings.section\",\n\t\t\t\tid: \"archived-sessions\",\n\t\t\t\torder: 100,\n\t\t\t\tlabel: () => t(\"settings.archivedSessions\"),\n\t\t\t\tlocale: NS,\n\t\t\t\tinject: () => ({\n\t\t\t\t\tuseArchived,\n\t\t\t\t\tuseSessionsList,\n\t\t\t\t\tunarchiveSession: async (sessionId) => {\n\t\t\t\t\t\tawait ctx.workspaces.unarchiveSession(sessionId);\n\t\t\t\t\t},\n\t\t\t\t\tdeleteSession: async (sessionId) => {\n\t\t\t\t\t\tawait ctx.workspaces.deleteSession(sessionId);\n\t\t\t\t\t}\n\t\t\t\t})\n\t\t\t}, ArchivedSessionsSection));\n\t\t}\n\t\t//#endregion\n\t\texports.apply = apply;\n",
  },
  {
    file: "../node_modules/@deepseek-ai/dsh-client-runtime/lib/client.js",
    original: "\t\t\t\tif (result.ok) this.installArchived(result.value.archivedSessionIds);\n\t\t\t\treturn result;\n\t\t\t}\n\t\t\t/**\n\t\t\t* Host-frame entry. Non-workspace frames are ignored so the runtime can\n\t\t\t* fan one host stream out to both object managers.\n",
    fixed: "\t\t\t\tif (result.ok) this.installArchived(result.value.archivedSessionIds);\n\t\t\t\treturn result;\n\t\t\t}\n\t\t\tasync unarchiveSession(sessionId) {\n\t\t\t\tconst { result } = await this.api.workspace.unarchiveSession({ sessionId });\n\t\t\t\tif (result.ok) this.installArchived(result.value.archivedSessionIds);\n\t\t\t\treturn result;\n\t\t\t}\n\t\t\tasync deleteSession(sessionId) {\n\t\t\t\tconst { result } = await this.api.sessions.delete({ sessionId });\n\t\t\t\treturn result;\n\t\t\t}\n\t\t\t/**\n\t\t\t* Host-frame entry. Non-workspace frames are ignored so the runtime can\n\t\t\t* fan one host stream out to both object managers.\n",
  },
  {
    file: "../node_modules/@deepseek-ai/dsh-client-runtime/lib/client.js",
    original: "\t\t\t\tconst result = await this.manager.archiveSession(sessionId);\n\t\t\t\tif (!result.ok) throw new Error(`session archive failed: ${result.error.code}: ${result.error.message}`);\n\t\t\t}\n\t\t\t/**\n\t\t\t* Move a session within its Workspace's manual order (DOM-insertBefore-like).\n\t\t\t* @param workspaceId - owning workspace.\n",
    fixed: "\t\t\t\tconst result = await this.manager.archiveSession(sessionId);\n\t\t\t\tif (!result.ok) throw new Error(`session archive failed: ${result.error.code}: ${result.error.message}`);\n\t\t\t}\n\t\t\tasync unarchiveSession(sessionId) {\n\t\t\t\tconst result = await this.manager.unarchiveSession(sessionId);\n\t\t\t\tif (!result.ok) throw new Error(`session unarchive failed: ${result.error.code}: ${result.error.message}`);\n\t\t\t}\n\t\t\tasync deleteSession(sessionId) {\n\t\t\t\tconst result = await this.manager.deleteSession(sessionId);\n\t\t\t\tif (!result.ok) throw new Error(`session delete failed: ${result.error.code}: ${result.error.message}`);\n\t\t\t\t// The deleted row leaves the list on the next pull; refresh now so\n\t\t\t\t// the UI drops it without waiting for a reconnect.\n\t\t\t\tawait this.ctx.get(\"sessions\")?.refresh?.();\n\t\t\t}\n\t\t\t/**\n\t\t\t* Move a session within its Workspace's manual order (DOM-insertBefore-like).\n\t\t\t* @param workspaceId - owning workspace.\n",
  },
  {
    file: "../node_modules/@deepseek-ai/dsh-host-apiproxy/lib/types/api-proxy.js",
    original: "                agent.cancel({ kind: 'user' }, { keepInbox: true });\n                return Promise.resolve(ok(request, { accepted: true }));\n            },\n        },\n        subagents: {\n            async list(request, signal) {\n",
    fixed: "                agent.cancel({ kind: 'user' }, { keepInbox: true });\n                return Promise.resolve(ok(request, { accepted: true }));\n            },\n            async delete(request) {\n                const { sessionId } = request.payload;\n                const sessions = ctx.get('sessions');\n                if (sessions?.get(sessionId) !== void 0) {\n                    return Promise.resolve(err(request, {\n                        code: 'session-live',\n                        message: 'session \"' + sessionId + '\" is running and cannot be deleted',\n                        details: { sessionId },\n                    }));\n                }\n                await ctx.sessionPersistence.delete(sessionId);\n                return Promise.resolve(ok(request, { deleted: true }));\n            },\n        },\n        subagents: {\n            async list(request, signal) {\n",
  },
  {
    file: "../node_modules/@deepseek-ai/dsh-host-apiproxy/lib/types/api-proxy.js",
    original: "                }\n                return ok(request, { archivedSessionIds: [...ctx.workspaceRegistry.archivedSessionIds] });\n            },\n        },\n        host: {\n            describe(request) {\n",
    fixed: "                }\n                return ok(request, { archivedSessionIds: [...ctx.workspaceRegistry.archivedSessionIds] });\n            },\n            async unarchiveSession(request) {\n                const { sessionId } = request.payload;\n                await ctx.workspaceRegistry.unarchiveSession(sessionId);\n                return ok(request, { archivedSessionIds: [...ctx.workspaceRegistry.archivedSessionIds] });\n            },\n        },\n        host: {\n            describe(request) {\n",
  },
  {
    file: "../node_modules/@deepseek-ai/dsh-host-apiproxy/lib/types/api/sessions.schema.js",
    original: "export const sessionCancelValueSchema = z.object({\n    accepted: z.literal(true),\n});\n//# sourceMappingURL=sessions.schema.js.map",
    fixed: "export const sessionCancelValueSchema = z.object({\n    accepted: z.literal(true),\n});\n/** session.delete request payload. */\nexport const sessionDeleteRequestSchema = z.object({\n    sessionId: sessionIdSchema,\n});\n/** session.delete response value: confirmation of permanent deletion. */\nexport const sessionDeleteValueSchema = z.object({\n    deleted: z.literal(true),\n});\n//# sourceMappingURL=sessions.schema.js.map",
  },
  {
    file: "../node_modules/@deepseek-ai/dsh-host-apiproxy/lib/types/api/rpc.schema.js",
    original: "    z.object({ code: z.literal('attachment-error'), message: z.string(), details: z.object({ reason: z.string() }) }),\n    z.object({ code: z.literal('queue-item-not-found'), message: z.string(), details: z.object({ itemId: z.string() }) }),\n    z.object({ code: z.literal('steer-unavailable'), message: z.string(), details: z.object({ itemId: z.string() }) }),\n    z.object({ code: z.literal('command-error'), message: z.string(), details: z.object({}) }),\n    z.object({ code: z.literal('unknown-command'), message: z.string(), details: z.object({}) }),\n    z.object({ code: z.literal('settings-rejected'), message: z.string(), details: z.object({ ns: z.string() }) }),\n",
    fixed: "    z.object({ code: z.literal('attachment-error'), message: z.string(), details: z.object({ reason: z.string() }) }),\n    z.object({ code: z.literal('queue-item-not-found'), message: z.string(), details: z.object({ itemId: z.string() }) }),\n    z.object({ code: z.literal('steer-unavailable'), message: z.string(), details: z.object({ itemId: z.string() }) }),\n    z.object({ code: z.literal('session-live'), message: z.string(), details: z.object({ sessionId: z.string() }) }),\n    z.object({ code: z.literal('command-error'), message: z.string(), details: z.object({}) }),\n    z.object({ code: z.literal('unknown-command'), message: z.string(), details: z.object({}) }),\n    z.object({ code: z.literal('settings-rejected'), message: z.string(), details: z.object({ ns: z.string() }) }),\n",
  },
  {
    file: "../node_modules/@deepseek-ai/dsh-host-apiproxy/lib/types/api/workspace.schema.js",
    original: "export const workspaceArchiveSessionValueSchema = z.object({\n    archivedSessionIds: z.array(sessionIdSchema),\n});\n//# sourceMappingURL=workspace.schema.js.map",
    fixed: "export const workspaceArchiveSessionValueSchema = z.object({\n    archivedSessionIds: z.array(sessionIdSchema),\n});\n/** workspace.unarchiveSession request payload. */\nexport const workspaceUnarchiveSessionRequestSchema = z.object({\n    sessionId: sessionIdSchema,\n});\n/** workspace.unarchiveSession response value: the full updated archive set. */\nexport const workspaceUnarchiveSessionValueSchema = z.object({\n    archivedSessionIds: z.array(sessionIdSchema),\n});\n//# sourceMappingURL=workspace.schema.js.map",
  },
  {
    file: "../node_modules/@deepseek-ai/dsh-host-apiproxy/lib/types/fetch/handler.js",
    original: "import { sessionLogQuerySchema } from \"../api/downloads.schema.js\";\nimport { RpcId } from \"../api/rpc.js\";\nimport { clientRequestSchema, clientResponseSchema } from \"../api/rpc.schema.js\";\nimport { sessionCancelRequestSchema, sessionAttachmentRequestSchema, sessionCreateRequestSchema, sessionForkRequestSchema, sessionHistoryRequestSchema, sessionListRequestSchema, sessionModelsRequestSchema, sessionPromptRequestSchema, sessionRenameRequestSchema, sessionSearchRequestSchema, sessionSelectModelRequestSchema, sessionUpdateQueueRequestSchema, } from \"../api/sessions.schema.js\";\nimport { hostCreateDirectoryRequestSchema, hostDescribeRequestSchema, hostListDirectoryRequestSchema, hostOpenPathRequestSchema, hostPickDirectoryRequestSchema, } from \"../api/host.schema.js\";\nimport { workspaceArchiveSessionRequestSchema, workspaceCreateRequestSchema, workspaceDeleteRequestSchema, workspaceInsertBeforeRequestSchema, workspaceInsertSessionBeforeRequestSchema, workspaceListRequestSchema, workspaceRenameRequestSchema, } from \"../api/workspace.schema.js\";\nimport { skillListRequestSchema } from \"../api/skills.schema.js\";\nimport { agentPresetCopyRequestSchema, agentPresetListRequestSchema, agentPresetOpenDocumentRequestSchema, agentPresetReadRequestSchema, agentPresetRemoveRequestSchema, agentPresetSelectRequestSchema, } from \"../api/agent-presets.schema.js\";\nimport { goalCreateRequestSchema, goalEditRequestSchema, goalPauseRequestSchema, goalResumeRequestSchema, goalCompleteRequestSchema, goalClearRequestSchema, } from \"../api/goals.schema.js\";\n",
    fixed: "import { sessionLogQuerySchema } from \"../api/downloads.schema.js\";\nimport { RpcId } from \"../api/rpc.js\";\nimport { clientRequestSchema, clientResponseSchema } from \"../api/rpc.schema.js\";\nimport { sessionCancelRequestSchema, sessionDeleteRequestSchema, sessionAttachmentRequestSchema, sessionCreateRequestSchema, sessionForkRequestSchema, sessionHistoryRequestSchema, sessionListRequestSchema, sessionModelsRequestSchema, sessionPromptRequestSchema, sessionRenameRequestSchema, sessionSearchRequestSchema, sessionSelectModelRequestSchema, sessionUpdateQueueRequestSchema, } from \"../api/sessions.schema.js\";\nimport { hostCreateDirectoryRequestSchema, hostDescribeRequestSchema, hostListDirectoryRequestSchema, hostOpenPathRequestSchema, hostPickDirectoryRequestSchema, } from \"../api/host.schema.js\";\nimport { workspaceArchiveSessionRequestSchema, workspaceCreateRequestSchema, workspaceDeleteRequestSchema, workspaceInsertBeforeRequestSchema, workspaceInsertSessionBeforeRequestSchema, workspaceListRequestSchema, workspaceRenameRequestSchema, workspaceUnarchiveSessionRequestSchema, } from \"../api/workspace.schema.js\";\nimport { skillListRequestSchema } from \"../api/skills.schema.js\";\nimport { agentPresetCopyRequestSchema, agentPresetListRequestSchema, agentPresetOpenDocumentRequestSchema, agentPresetReadRequestSchema, agentPresetRemoveRequestSchema, agentPresetSelectRequestSchema, } from \"../api/agent-presets.schema.js\";\nimport { goalCreateRequestSchema, goalEditRequestSchema, goalPauseRequestSchema, goalResumeRequestSchema, goalCompleteRequestSchema, goalClearRequestSchema, } from \"../api/goals.schema.js\";\n",
  },
  {
    file: "../node_modules/@deepseek-ai/dsh-host-apiproxy/lib/types/fetch/handler.js",
    original: "    'session.attachment': { schema: sessionAttachmentRequestSchema, invoke: (api, r) => api.sessions.attachment(r) },\n    'session.updateQueue': { schema: sessionUpdateQueueRequestSchema, invoke: (api, r) => api.sessions.updateQueue(r) },\n    'session.cancel': { schema: sessionCancelRequestSchema, invoke: (api, r) => api.sessions.cancel(r) },\n    'subagent.list': { schema: subagentListRequestSchema, invoke: (api, r, signal) => api.subagents.list(r, signal) },\n    'subagent.history': { schema: subagentHistoryRequestSchema, invoke: (api, r, signal) => api.subagents.history(r, signal) },\n    'subagent.prompt': { schema: subagentPromptRequestSchema, invoke: (api, r, signal) => api.subagents.prompt(r, signal) },\n",
    fixed: "    'session.attachment': { schema: sessionAttachmentRequestSchema, invoke: (api, r) => api.sessions.attachment(r) },\n    'session.updateQueue': { schema: sessionUpdateQueueRequestSchema, invoke: (api, r) => api.sessions.updateQueue(r) },\n    'session.cancel': { schema: sessionCancelRequestSchema, invoke: (api, r) => api.sessions.cancel(r) },\n    'session.delete': { schema: sessionDeleteRequestSchema, invoke: (api, r) => api.sessions.delete(r) },\n    'subagent.list': { schema: subagentListRequestSchema, invoke: (api, r, signal) => api.subagents.list(r, signal) },\n    'subagent.history': { schema: subagentHistoryRequestSchema, invoke: (api, r, signal) => api.subagents.history(r, signal) },\n    'subagent.prompt': { schema: subagentPromptRequestSchema, invoke: (api, r, signal) => api.subagents.prompt(r, signal) },\n",
  },
  {
    file: "../node_modules/@deepseek-ai/dsh-host-apiproxy/lib/types/fetch/handler.js",
    original: "    'workspace.insertBefore': { schema: workspaceInsertBeforeRequestSchema, invoke: (api, r) => api.workspace.insertBefore(r) },\n    'workspace.insertSessionBefore': { schema: workspaceInsertSessionBeforeRequestSchema, invoke: (api, r) => api.workspace.insertSessionBefore(r) },\n    'workspace.archiveSession': { schema: workspaceArchiveSessionRequestSchema, invoke: (api, r) => api.workspace.archiveSession(r) },\n    'skill.list': { schema: skillListRequestSchema, invoke: (api, r) => api.skills.list(r) },\n    'agentPreset.list': { schema: agentPresetListRequestSchema, invoke: (api, r) => api.agentPresets.list(r) },\n    'agentPreset.select': { schema: agentPresetSelectRequestSchema, invoke: (api, r) => api.agentPresets.select(r) },\n",
    fixed: "    'workspace.insertBefore': { schema: workspaceInsertBeforeRequestSchema, invoke: (api, r) => api.workspace.insertBefore(r) },\n    'workspace.insertSessionBefore': { schema: workspaceInsertSessionBeforeRequestSchema, invoke: (api, r) => api.workspace.insertSessionBefore(r) },\n    'workspace.archiveSession': { schema: workspaceArchiveSessionRequestSchema, invoke: (api, r) => api.workspace.archiveSession(r) },\n    'workspace.unarchiveSession': { schema: workspaceUnarchiveSessionRequestSchema, invoke: (api, r) => api.workspace.unarchiveSession(r) },\n    'skill.list': { schema: skillListRequestSchema, invoke: (api, r) => api.skills.list(r) },\n    'agentPreset.list': { schema: agentPresetListRequestSchema, invoke: (api, r) => api.agentPresets.list(r) },\n    'agentPreset.select': { schema: agentPresetSelectRequestSchema, invoke: (api, r) => api.agentPresets.select(r) },\n",
  },
  {
    file: "../node_modules/@deepseek-ai/dsh-host-apiproxy/lib/types/fetch/client.js",
    original: "import { rpcReceiptSchema, serverRequestSchema, serverResponseSchema } from \"../api/rpc.schema.js\";\nimport { hostFrameSchema, muxFrameSchema } from \"../api/events.schema.js\";\nimport { hostCreateDirectoryValueSchema, hostDescribeValueSchema, hostListDirectoryValueSchema, hostOpenPathValueSchema, hostPickDirectoryValueSchema, } from \"../api/host.schema.js\";\nimport { sessionCancelValueSchema, sessionAttachmentValueSchema, sessionCreateValueSchema, sessionForkValueSchema, sessionHistoryValueSchema, sessionListValueSchema, sessionModelsValueSchema, sessionPromptValueSchema, sessionRenameValueSchema, sessionSearchValueSchema, sessionSelectModelValueSchema, sessionUpdateQueueValueSchema, } from \"../api/sessions.schema.js\";\nimport { workspaceArchiveSessionValueSchema, workspaceCreateValueSchema, workspaceDeleteValueSchema, workspaceInsertBeforeValueSchema, workspaceInsertSessionBeforeValueSchema, workspaceListValueSchema, workspaceRenameValueSchema, } from \"../api/workspace.schema.js\";\nimport { skillListValueSchema } from \"../api/skills.schema.js\";\nimport { agentPresetCopyValueSchema, agentPresetListValueSchema, agentPresetOpenDocumentValueSchema, agentPresetReadValueSchema, agentPresetRemoveValueSchema, agentPresetSelectValueSchema, } from \"../api/agent-presets.schema.js\";\nimport { goalCreateValueSchema, goalEditValueSchema, goalPauseValueSchema, goalResumeValueSchema, goalCompleteValueSchema, goalClearValueSchema, } from \"../api/goals.schema.js\";\n",
    fixed: "import { rpcReceiptSchema, serverRequestSchema, serverResponseSchema } from \"../api/rpc.schema.js\";\nimport { hostFrameSchema, muxFrameSchema } from \"../api/events.schema.js\";\nimport { hostCreateDirectoryValueSchema, hostDescribeValueSchema, hostListDirectoryValueSchema, hostOpenPathValueSchema, hostPickDirectoryValueSchema, } from \"../api/host.schema.js\";\nimport { sessionCancelValueSchema, sessionDeleteValueSchema, sessionAttachmentValueSchema, sessionCreateValueSchema, sessionForkValueSchema, sessionHistoryValueSchema, sessionListValueSchema, sessionModelsValueSchema, sessionPromptValueSchema, sessionRenameValueSchema, sessionSearchValueSchema, sessionSelectModelValueSchema, sessionUpdateQueueValueSchema, } from \"../api/sessions.schema.js\";\nimport { workspaceArchiveSessionValueSchema, workspaceCreateValueSchema, workspaceDeleteValueSchema, workspaceUnarchiveSessionValueSchema, workspaceInsertBeforeValueSchema, workspaceInsertSessionBeforeValueSchema, workspaceListValueSchema, workspaceRenameValueSchema, } from \"../api/workspace.schema.js\";\nimport { skillListValueSchema } from \"../api/skills.schema.js\";\nimport { agentPresetCopyValueSchema, agentPresetListValueSchema, agentPresetOpenDocumentValueSchema, agentPresetReadValueSchema, agentPresetRemoveValueSchema, agentPresetSelectValueSchema, } from \"../api/agent-presets.schema.js\";\nimport { goalCreateValueSchema, goalEditValueSchema, goalPauseValueSchema, goalResumeValueSchema, goalCompleteValueSchema, goalClearValueSchema, } from \"../api/goals.schema.js\";\n",
  },
  {
    file: "../node_modules/@deepseek-ai/dsh-host-apiproxy/lib/types/fetch/client.js",
    original: "    'session.attachment': sessionAttachmentValueSchema,\n    'session.updateQueue': sessionUpdateQueueValueSchema,\n    'session.cancel': sessionCancelValueSchema,\n    'subagent.list': subagentListValueSchema,\n    'subagent.history': subagentHistoryValueSchema,\n    'subagent.prompt': subagentPromptValueSchema,\n",
    fixed: "    'session.attachment': sessionAttachmentValueSchema,\n    'session.updateQueue': sessionUpdateQueueValueSchema,\n    'session.cancel': sessionCancelValueSchema,\n    'session.delete': sessionDeleteValueSchema,\n    'subagent.list': subagentListValueSchema,\n    'subagent.history': subagentHistoryValueSchema,\n    'subagent.prompt': subagentPromptValueSchema,\n",
  },
  {
    file: "../node_modules/@deepseek-ai/dsh-host-apiproxy/lib/types/fetch/client.js",
    original: "    'workspace.insertBefore': workspaceInsertBeforeValueSchema,\n    'workspace.insertSessionBefore': workspaceInsertSessionBeforeValueSchema,\n    'workspace.archiveSession': workspaceArchiveSessionValueSchema,\n    'skill.list': skillListValueSchema,\n    'agentPreset.list': agentPresetListValueSchema,\n    'agentPreset.select': agentPresetSelectValueSchema,\n",
    fixed: "    'workspace.insertBefore': workspaceInsertBeforeValueSchema,\n    'workspace.insertSessionBefore': workspaceInsertSessionBeforeValueSchema,\n    'workspace.archiveSession': workspaceArchiveSessionValueSchema,\n'workspace.unarchiveSession': workspaceUnarchiveSessionValueSchema,\n    'skill.list': skillListValueSchema,\n    'agentPreset.list': agentPresetListValueSchema,\n    'agentPreset.select': agentPresetSelectValueSchema,\n",
  },
  {
    file: "../node_modules/@deepseek-ai/dsh-host-apiproxy/lib/types/fetch/client.js",
    original: "        attachment: (payload, signal) => this.callUnary('session.attachment', payload, signal),\n        updateQueue: (payload, signal) => this.callUnary('session.updateQueue', payload, signal),\n        cancel: (payload, signal) => this.callUnary('session.cancel', payload, signal),\n    };\n    subagents = {\n        list: (payload, signal) => this.callUnary('subagent.list', payload, signal),\n",
    fixed: "        attachment: (payload, signal) => this.callUnary('session.attachment', payload, signal),\n        updateQueue: (payload, signal) => this.callUnary('session.updateQueue', payload, signal),\n        cancel: (payload, signal) => this.callUnary('session.cancel', payload, signal),\n    delete: (payload, signal) => this.callUnary('session.delete', payload, signal),\n    };\n    subagents = {\n        list: (payload, signal) => this.callUnary('subagent.list', payload, signal),\n",
  },
  {
    file: "../node_modules/@deepseek-ai/dsh-host-apiproxy/lib/types/fetch/client.js",
    original: "        insertBefore: (payload, signal) => this.callUnary('workspace.insertBefore', payload, signal),\n        insertSessionBefore: (payload, signal) => this.callUnary('workspace.insertSessionBefore', payload, signal),\n        archiveSession: (payload, signal) => this.callUnary('workspace.archiveSession', payload, signal),\n    };\n    skills = {\n        list: (payload, signal) => this.callUnary('skill.list', payload, signal),\n",
    fixed: "        insertBefore: (payload, signal) => this.callUnary('workspace.insertBefore', payload, signal),\n        insertSessionBefore: (payload, signal) => this.callUnary('workspace.insertSessionBefore', payload, signal),\n        archiveSession: (payload, signal) => this.callUnary('workspace.archiveSession', payload, signal),\n    unarchiveSession: (payload, signal) => this.callUnary('workspace.unarchiveSession', payload, signal),\n    };\n    skills = {\n        list: (payload, signal) => this.callUnary('skill.list', payload, signal),\n",
  },
  {
    file: "../node_modules/@deepseek-ai/dsh-workspace/lib/index.js",
    original: "\t\t\t});\n\t\t});\n\t}\n\t/**\n\t* Whether a session is live, header-indexed, or present in a fresh\n\t* persistence listing. Only a definite miss returns false — a failing\n",
    fixed: "\t\t\t});\n\t\t});\n\t}\n\tunarchiveSession(sessionId) {\n\t\treturn this.enqueueOperation(async () => {\n\t\t\tif (!this.requireState().archivedSessionIds.includes(sessionId)) return;\n\t\t\tconst state = this.requireState();\n\t\t\tawait this.setState({\n\t\t\t\t...state,\n\t\t\t\tarchivedSessionIds: state.archivedSessionIds.filter(id => id !== sessionId)\n\t\t\t});\n\t\t});\n\t}\n\t/**\n\t* Whether a session is live, header-indexed, or present in a fresh\n\t* persistence listing. Only a definite miss returns false — a failing\n",
  },
  {
    file: "../node_modules/@deepseek-ai/dsh-workspace/lib/index.js",
    original: "\t\tconst entity = this.entities.get(id);\n\t\tif (entity === void 0) return false;\n\t\tconst state = this.requireState();\n\t\tconst nextState = {\n\t\t\tinitialized: true,\n\t\t\tworkspaceIds: state.workspaceIds.filter((workspaceId) => workspaceId !== id),\n\t\t\tarchivedSessionIds: state.archivedSessionIds\n\t\t};\n\t\tawait this.setState({\n\t\t\t...nextState,\n",
    fixed: "\t\tconst entity = this.entities.get(id);\n\t\tif (entity === void 0) return false;\n\t\tconst state = this.requireState();\n\t\t// Deleting a workspace permanently deletes every session it accounted.\n\t\t// Live sessions (a running writer owns their artifacts) are left in\n\t\t// place; they surface under the ungrouped bucket once they finish.\n\t\tconst record = this.requireTable().get(id);\n\t\tconst sessionIds = record?.sessionIds ?? [];\n\t\tconst sessions = this.ctx.get(\"sessions\");\n\t\tfor (const sessionId of sessionIds) {\n\t\t\tif (sessions?.get(sessionId) !== void 0) {\n\t\t\t\tthis.ctx.logger.warn(\"workspace \" + id + \" kept live session \" + sessionId + \" (running agent)\");\n\t\t\t\tcontinue;\n\t\t\t}\n\t\t\tawait this.ctx.sessionPersistence.delete(sessionId);\n\t\t}\n\t\tconst nextState = {\n\t\t\tinitialized: true,\n\t\t\tworkspaceIds: state.workspaceIds.filter((workspaceId) => workspaceId !== id),\n\t\t\tarchivedSessionIds: state.archivedSessionIds.filter((sessionId) => !sessionIds.includes(sessionId))\n\t\t};\n\t\tawait this.setState({\n\t\t\t...nextState,\n",
  },
  {
    file: "../node_modules/@deepseek-ai/dsh-session-persistence-jsonl/lib/index.js",
    original: "\t\tsignal?.throwIfAborted();\n\t\treturn snapshots;\n\t}\n\tasync listArtifacts(signal) {\n\t\tsignal?.throwIfAborted();\n\t\tawait this.ensureRootEncoding();\n",
    fixed: "\t\tsignal?.throwIfAborted();\n\t\treturn snapshots;\n\t}\n\t/**\n\t* Permanently delete one session's artifact directory, so list and load\n\t* stop seeing it. Unknown ids and sessions without a materialized artifact\n\t* resolve without error. A session with a live writer must be detached\n\t* before this call.\n\t* @param id - the persisted session to delete.\n\t* @param signal - optional cancellation for backend deletion work.\n\t*/\n\tasync delete(id, signal) {\n\t\tsignal?.throwIfAborted();\n\t\tconst artifacts = await this.listArtifacts(signal);\n\t\tconst artifact = artifacts.find((item) => item.header.id === id);\n\t\tif (artifact === void 0) return;\n\t\tsignal?.throwIfAborted();\n\t\tawait rm(dirname(artifact.path), { recursive: true, force: true });\n\t}\n\tasync listArtifacts(signal) {\n\t\tsignal?.throwIfAborted();\n\t\tawait this.ensureRootEncoding();\n",
  },
  {
    file: "../node_modules/@deepseek-ai/dsh-host-directory-picker-native/lib/worker.cjs",
    original: "* Read a NUL-terminated UTF-16 string at a native address. koffi's\n* `_Out_ void **` out-params surface a raw address, and\n* `koffi.decode(addr, 'str16')` would dereference it as a pointer — crash\n* on real Windows — so view the memory directly instead.\n*/\nfunction readUtf16(koffi, address) {\n\tconst bytes = Buffer.from(koffi.view(address, 32768));\n\tlet end = 0;\n\twhile (end + 1 < bytes.length && bytes[end] !== 0) end += 2;\n\treturn bytes.toString(\"utf16le\", 0, end);\n}\nconst COINIT_APARTMENTTHREADED = 2;\nconst CLSCTX_INPROC_SERVER = 1;\n",
    fixed: "* Read a NUL-terminated UTF-16 string at a native address. koffi's\n* `_Out_ void **` out-params surface a raw address, and\n* `koffi.decode(addr, 'str16')` would dereference it as a pointer — crash\n* on real Windows. `koffi.view()` cannot be used either: under\n* Electron-as-node (how the desktop shell runs the bundled dsh) koffi 3.1.x\n* aborts the process natively inside view() with\n* `FATAL ERROR: Error::New napi_get_last_error_info`, taking the worker down\n* before it can report the picked path. Copy the string with RtlMoveMemory\n* into plain JS buffers instead — a path that only uses koffi.call, which is\n* safe on both plain Node and Electron-as-node.\n*/\nfunction readUtf16(koffi, address) {\n\tif (!address) return \"\";\n\tconst base = typeof address === \"bigint\" ? Number(address) : address;\n\tconst kernel32 = koffi.load(\"kernel32.dll\");\n\tconst copyMemory = kernel32.func(\"__stdcall\", \"RtlMoveMemory\", \"void\", [\"void *\", \"void *\", \"uintptr\"]);\n\tconst CHUNK = 512;\n\tconst chunks = [];\n\tlet offset = 0;\n\tfor (let i = 0; i < 2048; i++) {\n\t\tconst dest = Buffer.alloc(CHUNK);\n\t\tcopyMemory(dest, base + offset, CHUNK);\n\t\tlet end = -1;\n\t\tfor (let j = 0; j + 1 < dest.length; j += 2) {\n\t\t\tif (dest[j] === 0 && dest[j + 1] === 0) {\n\t\t\t\tend = j;\n\t\t\t\tbreak;\n\t\t\t}\n\t\t}\n\t\tif (end >= 0) {\n\t\t\tchunks.push(dest.subarray(0, end));\n\t\t\tbreak;\n\t\t}\n\t\tchunks.push(dest);\n\t\toffset += CHUNK;\n\t}\n\treturn Buffer.concat(chunks).toString(\"utf16le\");\n}\nconst COINIT_APARTMENTTHREADED = 2;\nconst CLSCTX_INPROC_SERVER = 1;\n",
  },
]

let patched = 0
for (const patch of PATCHES) {
  const file = fileURLToPath(new URL(patch.file, import.meta.url))
  if (!existsSync(file)) {
    console.log('[patch-dsh] ' + patch.file + ' not found — skipping')
    continue
  }
  const source = readFileSync(file, 'utf8')
  // "Already carries the fix" is decided by the fixed text itself: the entry
  // applies only while the original block is present and the fixed block is not.
  if (source.includes(patch.fixed)) {
    console.log('[patch-dsh] ' + patch.file + ' already carries the fix — no-op')
    continue
  }
  if (!source.includes(patch.original)) {
    console.error('[patch-dsh] ERROR: ' + patch.file + ' does not match the expected upstream content; cannot apply the patch.')
    console.error('If @deepseek-ai/dsh was upgraded, check whether the fixes landed upstream, then remove this script and the package.json postinstall entry.')
    process.exit(1)
  }
  writeFileSync(file, source.replace(patch.original, patch.fixed))
  console.log('[patch-dsh] patched ' + patch.file)
  patched += 1
}
console.log('[patch-dsh] ' + patched + ' patch(es) applied')
